//start - license
/*
 * Copyright (c) 2025 Ashera Cordova
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
//end - license
/* Generated By:JavaCC: Do not edit this line. EvaluatorConstants.java */
package com.ashera.css;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface EvaluatorConstants {

 /** End of File. */
  int EOF = 0;
 /** RegularExpression Id. */
  int MEDIA = 5;
 /** RegularExpression Id. */
  int AND_TOKEN = 6;
 /** RegularExpression Id. */
  int ANY = 7;
 /** RegularExpression Id. */
  int orientation = 8;
 /** RegularExpression Id. */
  int superview = 9;
 /** RegularExpression Id. */
  int relation = 10;
 /** RegularExpression Id. */
  int CSS_VAR = 11;
 /** RegularExpression Id. */
  int OPEN_BRACKET = 12;
 /** RegularExpression Id. */
  int CLOSE_BRACKET = 13;
 /** RegularExpression Id. */
  int COLON = 14;
 /** RegularExpression Id. */
  int SEMI_COLON = 15;
 /** RegularExpression Id. */
  int CSS_VAR_WHITE_SPACE = 16;

 /** Lexical state. */
  int DEFAULT = 0;

 /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"@media only screen and \"",
    "\"and \"",
    "\"a\"",
    "<orientation>",
    "\"|\"",
    "<relation>",
    "<CSS_VAR>",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\";\"",
    "<CSS_VAR_WHITE_SPACE>",
    "\"(\"",
    "\")\"",
  };

}
